{% set name = "filewise" %}
{% set version = "3.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=68.0
    - wheel
  run:
    - python >=3.10
    - pip
    - numpy >=1.21.0,<2.0.0
    - pandas >=1.3.0,<2.0.0
    # Add other dependencies as needed

test:
  imports:
    - filewise

about:
  home: https://github.com/EusDancerDev/filewise
  license: MIT
  license_file: LICENSE
  summary: Python package filewise
  doc_url: https://github.com/EusDancerDev/filewise#readme
  dev_url: https://github.com/EusDancerDev/filewise.git

extra:
  recipe-maintainers:
    - EusDancerDev
