{% set name = "filewise" %}
{% set version = "3.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=68.0
    - wheel
  run:
    - python >=3.10
    - pip
    - numpy >=2.2.3
    - pandas >=2.2.3
    - openpyxl >=3.0.0
    # pygenutils, paramlib: PyPI pins via post-link.sh

test:
  imports:
    - filewise
  commands:
    - python -c "import filewise; print(filewise.__version__)"

about:
  home: https://github.com/EusDancerDev/filewise
  license: MIT
  license_file: LICENSE
  summary: Python package filewise
  doc_url: https://github.com/EusDancerDev/filewise#readme
  dev_url: https://github.com/EusDancerDev/filewise.git

extra:
  recipe-maintainers:
    - EusDancerDev
